INSERT INTO House (id, version, address) VALUES (1, 0, 'ул.Цюрупы, 16');

INSERT INTO House (id, version, address) VALUES (2, 0, 'ул.Лунина, 7');

INSERT INTO Person (id, version, first_name, age) VALUES (1, 0, 'Пётр', 20);

INSERT INTO Person (id, version, first_name, age) VALUES (2, 0, 'John', 25);

INSERT INTO Person_House (person_id, house_id) VALUES (1, 1);

INSERT INTO Person_House (person_id, house_id) VALUES (1, 2);

INSERT INTO ORGANIZATION (ID, NAME, FULL_NAME, INN, KPP, ADDRESS, PHONE, IS_ACTIVE) VALUES (SEQ_ORGANIZATION.nextval, 'starOrg', 'Саратовские авиалинии', '454555', '5600114', 'г.Саратов, ул.Ленина,57', '884526558', 1);

INSERT INTO ORGANIZATION (ID, NAME, FULL_NAME, INN, KPP, ADDRESS, PHONE, IS_ACTIVE) VALUES (SEQ_ORGANIZATION.nextval, 'tourOut', 'Туристическая компания', '111222', '5896321', 'г. Москва, ул. Набережная,20', '945225488', 1);

INSERT INTO ORGANIZATION (ID, NAME, FULL_NAME, INN, KPP, ADDRESS, PHONE, IS_ACTIVE) VALUES (SEQ_ORGANIZATION.nextval, 'teploTek', 'Комерческая фирма', '224466', '5554441', 'г. Орел, ул. Победы,2', '888666521', 1);

INSERT INTO OFFICE (ID, ORG_ID, NAME, ADDRESS, PHONE, IS_ACTIVE) VALUES (SEQ_OFFICE.nextval, '1', 'SarOfficeOne', 'г. Саратов ул. Пушкина, 51',
'256333', 1);

INSERT INTO OFFICE (ID, ORG_ID, NAME, ADDRESS, PHONE, IS_ACTIVE) VALUES (SEQ_OFFICE.nextval, '1', 'SarOfficeTwo', 'г. Саратов ул. Кирова, 66',
'256111', 1);

INSERT INTO OFFICE (ID, ORG_ID, NAME, ADDRESS, PHONE, IS_ACTIVE) VALUES (SEQ_OFFICE.nextval, '2', 'MosOffice', 'г. Москва ул. Верхняя, 66',
'205555', 1);

INSERT INTO OFFICE (ID, ORG_ID, NAME, ADDRESS, PHONE, IS_ACTIVE) VALUES (SEQ_OFFICE.nextval, '2', 'MosOfficeTwo', 'г. Москва ул. Попова, 74',
'555656', 1);

INSERT INTO OFFICE (ID, ORG_ID, NAME, ADDRESS, PHONE, IS_ACTIVE) VALUES (SEQ_OFFICE.nextval, '2', 'MosOfficeThree', 'г. Москва ул. Рахова, 20',
'474747', 1);

INSERT INTO OFFICE (ID, ORG_ID, NAME, ADDRESS, PHONE, IS_ACTIVE) VALUES (SEQ_OFFICE.nextval, '3', 'OrOfficeOne', 'г. Орел ул. Зимняя, 26',
'222111', 1);

INSERT INTO OFFICE (ID, ORG_ID, NAME, ADDRESS, PHONE, IS_ACTIVE) VALUES (SEQ_OFFICE.nextval, '3', 'OrOfficeTwo', 'г. Орел ул. Михайлова, 7',
'777666', 1);

INSERT INTO USER_DOCS (ID, DOC_CODE, DOC_NAME, DOC_NUMBER, DOC_DATE) VALUES (SEQ_USER_DOCS.nextval, '001', 'паспорт',
 '100', '25.12.85');

INSERT INTO USER_DOCS (ID, DOC_CODE, DOC_NAME, DOC_NUMBER, DOC_DATE) VALUES (SEQ_USER_DOCS.nextval, '002', 'паспорт',
 '001', '14.07.80');

INSERT INTO USER_DOCS (ID, DOC_CODE, DOC_NAME, DOC_NUMBER, DOC_DATE) VALUES (SEQ_USER_DOCS.nextval, '005', 'паспорт',
'002', '05.07.85');

INSERT INTO USER_DOCS (ID, DOC_CODE, DOC_NAME, DOC_NUMBER, DOC_DATE) VALUES (SEQ_USER_DOCS.nextval, '074', 'паспорт',
'005', '22.03.81');

INSERT INTO USER_DOCS (ID, DOC_CODE, DOC_NAME, DOC_NUMBER, DOC_DATE) VALUES (SEQ_USER_DOCS.nextval, '054', 'паспорт',
 '006', '15.08.83');

INSERT INTO USER_DOCS (ID, DOC_CODE, DOC_NAME, DOC_NUMBER, DOC_DATE) VALUES (SEQ_USER_DOCS.nextval, '087', 'паспорт',
 '040', '23.07.85');

INSERT INTO USER_DOCS (ID, DOC_CODE, DOC_NAME, DOC_NUMBER, DOC_DATE) VALUES (SEQ_USER_DOCS.nextval, '055', 'паспорт',
 '044', '13.07.85');

INSERT INTO USER_DOCS (ID, DOC_CODE, DOC_NAME, DOC_NUMBER, DOC_DATE) VALUES (SEQ_USER_DOCS.nextval, '082', 'паспорт',
 '033', '05.08.89');

INSERT INTO USER_DOCS (ID, DOC_CODE, DOC_NAME, DOC_NUMBER, DOC_DATE) VALUES (SEQ_USER_DOCS.nextval, '088', 'паспорт',
'041', '07.09.88');

INSERT INTO USER_DOCS (ID, DOC_CODE, DOC_NAME, DOC_NUMBER, DOC_DATE) VALUES (SEQ_USER_DOCS.nextval, '010', 'паспорт',
 '083', '07.04.79');

INSERT INTO USER_DOCS (ID, DOC_CODE, DOC_NAME, DOC_NUMBER, DOC_DATE) VALUES (SEQ_USER_DOCS.nextval, '043', 'паспорт',
'011', '25.11.89');

INSERT INTO USER_DOCS (ID, DOC_CODE, DOC_NAME, DOC_NUMBER, DOC_DATE) VALUES (SEQ_USER_DOCS.nextval, '060', 'паспорт',
 '033', '17.05.90');

INSERT INTO USER_BELL (ID, FIRST_NAME, SECOND_NAME, MIDDLE_NAME, POSITION, PHONE,
CITIZENSHIP_NAME, CITIZENSHIP_CODE, OFFICE_ID, IS_IDENTIFIED,USER_DOCS_ID) VALUES (SEQ_USER_BELL.nextval, 'Сергей', 'Иванович', 'Сочнев', 'менеджер',
 '999999','Россия', '64', '1', 1,1);

INSERT INTO USER_BELL (ID, FIRST_NAME, SECOND_NAME, MIDDLE_NAME, POSITION, PHONE,
CITIZENSHIP_NAME, CITIZENSHIP_CODE, OFFICE_ID, IS_IDENTIFIED,USER_DOCS_ID) VALUES (SEQ_USER_BELL.nextval, 'Александр', 'Александр', 'Киселев', 'диспетчер',
'999991',  'Россия', '63', '1', 1,2);

INSERT INTO USER_BELL (ID, FIRST_NAME, SECOND_NAME, MIDDLE_NAME, POSITION, PHONE,
CITIZENSHIP_NAME, CITIZENSHIP_CODE, OFFICE_ID, IS_IDENTIFIED,USER_DOCS_ID) VALUES (SEQ_USER_BELL.nextval, 'Михаил', 'Сергеевич', 'Светлов', 'менеджер',
'999990',  'Россия', '60', '2', 1,3);

INSERT INTO USER_BELL (ID, FIRST_NAME, SECOND_NAME, MIDDLE_NAME, POSITION, PHONE,
CITIZENSHIP_NAME, CITIZENSHIP_CODE, OFFICE_ID, IS_IDENTIFIED,USER_DOCS_ID) VALUES (SEQ_USER_BELL.nextval, 'Андрей', 'Иванович', 'Свердлов', 'менеджер',
'666669',  'Россия', '22', '2', 1,4);

INSERT INTO USER_BELL (ID, FIRST_NAME, SECOND_NAME, MIDDLE_NAME, POSITION, PHONE,
CITIZENSHIP_NAME, CITIZENSHIP_CODE, OFFICE_ID, IS_IDENTIFIED,USER_DOCS_ID) VALUES (SEQ_USER_BELL.nextval, 'Владимир', 'Владимирович', 'Емелин', 'менеджер',
'666668',  'Россия', '23', '3', 1,5);

INSERT INTO USER_BELL (ID, FIRST_NAME, SECOND_NAME, MIDDLE_NAME, POSITION, PHONE,
CITIZENSHIP_NAME, CITIZENSHIP_CODE, OFFICE_ID, IS_IDENTIFIED,USER_DOCS_ID) VALUES (SEQ_USER_BELL.nextval, 'Сергей', 'Анатольевыич', 'Кац', 'менеджер',
 '666667','Россия', '26', '3', 1,6);

INSERT INTO  USER_BELL  (ID, FIRST_NAME, SECOND_NAME, MIDDLE_NAME, POSITION, PHONE,
CITIZENSHIP_NAME, CITIZENSHIP_CODE, OFFICE_ID, IS_IDENTIFIED,USER_DOCS_ID) VALUES (SEQ_USER_BELL.nextval, 'Стас', 'Алексеевич', 'Милов', 'менеджер',
'666665','Россия', '54', '4', 1,7);

INSERT INTO USER_BELL (ID, FIRST_NAME, SECOND_NAME, MIDDLE_NAME, POSITION, PHONE,
CITIZENSHIP_NAME, CITIZENSHIP_CODE, OFFICE_ID, IS_IDENTIFIED,USER_DOCS_ID) VALUES (SEQ_USER_BELL.nextval, 'Алексей', 'Михайлович', 'Пономарев', 'менеджер',
'666664',  'Россия', '55', '5', 1,8);

INSERT INTO USER_BELL (ID, FIRST_NAME, SECOND_NAME, MIDDLE_NAME, POSITION, PHONE,
CITIZENSHIP_NAME, CITIZENSHIP_CODE, OFFICE_ID, IS_IDENTIFIED,USER_DOCS_ID) VALUES (SEQ_USER_BELL.nextval, 'Андрей', 'Петрович', 'Вилков', 'менеджер',
 '666663','Россия', '50', '5', 1,9);

INSERT INTO USER_BELL (ID, FIRST_NAME, SECOND_NAME, MIDDLE_NAME, POSITION, PHONE,
CITIZENSHIP_NAME, CITIZENSHIP_CODE, OFFICE_ID, IS_IDENTIFIED,USER_DOCS_ID) VALUES (SEQ_USER_BELL.nextval, 'Евгений', 'Ильич', 'Сорокин', 'менеджер',
 '666662','Россия', '53', '6', 1,10);

INSERT INTO USER_BELL (ID, FIRST_NAME, SECOND_NAME, MIDDLE_NAME, POSITION, PHONE,
CITIZENSHIP_NAME, CITIZENSHIP_CODE, OFFICE_ID, IS_IDENTIFIED,USER_DOCS_ID) VALUES (SEQ_USER_BELL.nextval, 'Руслан', 'Иванович', 'Попов', 'менеджер',
'555559', 'Россия', '52', '6', 1,11);

INSERT INTO USER_BELL (ID, FIRST_NAME, SECOND_NAME, MIDDLE_NAME, POSITION, PHONE,
CITIZENSHIP_NAME, CITIZENSHIP_CODE, OFFICE_ID, IS_IDENTIFIED,USER_DOCS_ID) VALUES (SEQ_USER_BELL.nextval, 'Игорь', 'Владимирович', 'Давлетов', 'менеджер',
'555558', 'Россия', '51', '7', 1,12);
