CREATE TABLE IF NOT EXISTS Person (
    id         INTEGER  PRIMARY KEY AUTO_INCREMENT,
    version    INTEGER NOT NULL,
    first_name VARCHAR(50) NOT NULL,
    age        INTEGER  NOT NULL
);

CREATE TABLE IF NOT EXISTS House (
    id         INTEGER  PRIMARY KEY AUTO_INCREMENT,
    version    INTEGER NOT NULL,
    address    VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS Person_House (
    person_id   INTEGER  NOT NULL,
    house_id    INTEGER  NOT NULL,

    PRIMARY KEY (person_id, house_id)
);

CREATE TABLE IF NOT EXISTS Organization (
    id           INTEGER  PRIMARY KEY AUTO_INCREMENT,
    name         VARCHAR(50),
    full_name    VARCHAR(50),
    inn          VARCHAR(50),
    kpp          VARCHAR(50),
    address      VARCHAR(50),
    phone        VARCHAR(50),
    is_Active    NUMBER(1) NOT NULL
);
 COMMENT ON COLUMN "ORGANIZATION"."ID" IS 'ID';
   COMMENT ON COLUMN "ORGANIZATION"."NAME" IS 'ИМЯ';
   COMMENT ON COLUMN "ORGANIZATION"."FULL_NAME" IS 'ПОЛНОЕ_ИМЯ';
   COMMENT ON COLUMN "ORGANIZATION"."INN" IS 'ИНН';
   COMMENT ON COLUMN "ORGANIZATION"."KPP" IS 'КПП';
   COMMENT ON COLUMN "ORGANIZATION"."ADDRESS" IS 'АДРЕС';
   COMMENT ON COLUMN "ORGANIZATION"."PHONE" IS 'ТЕЛЕФОН';
   COMMENT ON COLUMN "ORGANIZATION"."IS_ACTIVE" IS 'СОСТОЯНИЕ';

CREATE TABLE IF NOT EXISTS Office (
    id          INTEGER  PRIMARY KEY AUTO_INCREMENT,
    org_Id      VARCHAR(50),
    name        VARCHAR(50),
    address     VARCHAR(50),
    phone       VARCHAR(50),
    is_Active   NUMBER (1) NOT NULL
);
COMMENT ON COLUMN "OFFICE"."ID" IS 'ID';
   COMMENT ON COLUMN "OFFICE"."ORG_ID" IS 'ID_ORGANIZATION';
   COMMENT ON COLUMN "OFFICE"."NAME" IS 'ИМЯ';
   COMMENT ON COLUMN "OFFICE"."ADDRESS" IS 'АДРЕС';
   COMMENT ON COLUMN "OFFICE"."PHONE" IS 'ТЕЛЕФОН';
   COMMENT ON COLUMN "OFFICE"."IS_ACTIVE" IS 'СОСТОЯНИЕ';

CREATE TABLE IF NOT EXISTS User_Docs (
    id                 INTEGER  PRIMARY KEY AUTO_INCREMENT,
     doc_Code          VARCHAR(50),
     doc_Name          VARCHAR(50),
     doc_Number        VARCHAR(50),
     doc_Date           VARCHAR(50),
);
COMMENT ON COLUMN "USER_DOCS"."ID" IS 'ID';
   COMMENT ON COLUMN "USER_DOCS"."DOC_CODE" IS 'код документа ';
   COMMENT ON COLUMN "USER_DOCS"."DOC_NAME" IS 'имя документа';
   COMMENT ON COLUMN "USER_DOCS"."DOC_NUMBER" IS 'номер документа';
   COMMENT ON COLUMN "USER_DOCS"."DOC_DATE" IS 'дата созд док-та';

CREATE TABLE IF NOT EXISTS User_Bell (
    id                   INTEGER  PRIMARY KEY AUTO_INCREMENT,
    first_Name           VARCHAR(50),
    second_Name          VARCHAR(50),
    middle_Name          VARCHAR(50),
    position             VARCHAR(50),
    phone                VARCHAR(50),
     citizenship_Name    VARCHAR(50),
     citizenship_Code    VARCHAR(50),
     office_Id           VARCHAR(50),
     user_Docs_Id        INTEGER ,
     is_Identified       NUMBER(1) NOT NULL
);
COMMENT ON COLUMN "USER_BELL"."ID" IS 'ID';
   COMMENT ON COLUMN "USER_BELL"."FIRST_NAME" IS 'ИМЯ';
   COMMENT ON COLUMN "USER_BELL"."SECOND_NAME" IS 'ФАМИЛИЯ';
   COMMENT ON COLUMN "USER_BELL"."MIDDLE_NAME" IS 'ОТЧЕСТВО';
   COMMENT ON COLUMN "USER_BELL"."POSITION" IS 'ДОЛЖНОСТЬ';
   COMMENT ON COLUMN "USER_BELL"."PHONE" IS 'НОМЕР ТЕЛЕВОНА';
   COMMENT ON COLUMN "USER_BELL"."CITIZENSHIP_NAME" IS 'ГРАЖДАНСТВО';
   COMMENT ON COLUMN "USER_BELL"."CITIZENSHIP_CODE" IS 'КОД СТРАНЫ';
   COMMENT ON COLUMN "USER_BELL"."OFFICE_ID" IS 'OFFICE_ID';
   COMMENT ON COLUMN "USER_BELL"."IS_IDENTIFIED" IS 'СОСТОЯНИЕ';
   COMMENT ON COLUMN "USER_BELL"."USER_DOCS_ID" IS 'USER_DOCS_ID';


CREATE INDEX IX_Person_House_Id ON Person_House (house_id);
ALTER TABLE Person_House ADD FOREIGN KEY (house_id) REFERENCES House(id);

CREATE INDEX IX_House_Person_Id ON Person_House (person_id);
ALTER TABLE Person_House ADD FOREIGN KEY (person_id) REFERENCES Person(id);

ALTER TABLE User_Bell ADD FOREIGN KEY (user_docs_id) REFERENCES User_Docs(id);

CREATE SEQUENCE SEQ_OFFICE MINVALUE 1 INCREMENT BY 1;

CREATE SEQUENCE SEQ_ORGANIZATION MINVALUE 1 INCREMENT BY 1;

CREATE SEQUENCE SEQ_USER_BELL MINVALUE 1 INCREMENT BY 1;

CREATE SEQUENCE SEQ_USER_DOCS MINVALUE 1 INCREMENT BY 1;